version: '3.4'

services:
  courselitweb:
    image: courselitweb
    build:
      context: apps/web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
